FROM php:8.2-cli

# Install PostgreSQL extensions
RUN apt-get update && apt-get install -y libpq-dev \
    && docker-php-ext-install pgsql pdo_pgsql

# Copy app files to container
COPY . /var/www/html

# Set working directory
WORKDIR /var/www/html

# Expose port used by PHP built-in server
EXPOSE 10000

# Start PHP server
CMD ["php", "-S", "0.0.0.0:10000"]
